# Generated by Django 4.2.2 on 2023-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('año_publicacion', models.IntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('genero', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
                ('portada', models.ImageField(upload_to='libros/')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=150)),
                ('año_lanzamiento', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('portada', models.ImageField(upload_to='peliculas/')),
            ],
        ),
    ]
