# Generated by Django 4.2.2 on 2023-07-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioCine', '0003_alter_comentariolibro_comentario_alter_libro_portada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentariolibro',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='comentariolibro',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosLibros', to='AppBiblioCine.libro'),
        ),
        migrations.AlterField(
            model_name='comentariolibro',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=150),
        ),
    ]
