# Generated by Django 4.2.2 on 2023-07-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioCine', '0005_alter_libro_portada_alter_pelicula_portada_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
