# Generated by Django 4.2.2 on 2023-07-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblioCine', '0008_remove_comentariopelicula_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='recomendacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
